Vagrant.configure("2") do |config|
    config.vm.box = "#{ENV['DISTR']}/#{ENV['OS']}"
    if ENV["BOX_VER"] != ''
       config.vm.box_version = ENV["BOX_VER"]
    end

    config.vm.provider "virtualbox" do |v|
             v.customize ["modifyvm", :id, "--memory", "#{ENV['RAM']}"] #<= total RAM.
             v.customize ["modifyvm", :id, "--cpus", "#{ENV['CPU']}"] #<= total CPU.
             v.customize ["modifyvm", :id, "--ioapic", "on"]
    end

    config.vm.define 'ubuntu'

    config.vm.hostname = "host4test"

    if ENV['TEST_CASE'] != '--production-install'
       config.vm.provision "shell", inline: "rm -rf /tmp/docs && mkdir -p /tmp/docs && chown vagrant:vagrant /tmp/docs"
       config.vm.provision "file", source: "../../../OneClickInstall-Docs/.", destination: "/tmp/docs/"
    end

    config.vm.provision "file", source: "./post-install.sh", destination: "/tmp/post-install.sh"

    config.vm.provision "shell", path: './install.sh', :args => "#{ENV['DOWNLOAD_SCRIPT']} #{ENV['VER']} #{ENV['TEST_REPO']} #{ENV['IT']} #{ENV['ARGUMENTS']}"

    # Prevent SharedFoldersEnableSymlinksCreate errors
    config.vm.synced_folder ".", "/vagrant", disabled: true
end
